only show the create event menu item if it is a teacher
2020SE691T2/RecessApplication pull request #112
Opened 2021-02-07 01:53 UTC by msknobloch2

closes #88 

dont show the create event option in the menu bar if you are not a teacher

2021-02-07 14:14 UTC, jonathanmcdaniel requested changes
Can we store the user's role in session storage when they first log in and then check against that instead of doing all these network calls? Having a network call in the menu bar will do it on _every_ page that loads, and then on the create event page it might be slow and the user may see a flash of the page before getting redirected. Doing the call once on login would be faster and more secure.

2021-02-07 14:16 UTC, msknobloch2 commented
> Can we store the user's role in session storage when they first log in and then check against that instead of doing all these network calls? Having a network call in the menu bar will do it on _every_ page that loads, and then on the create event page it might be slow and the user may see a flash of the page before getting redirected. Doing the call once on login would be faster and more secure.

Thats smarter.  I will change that

2021-02-07 14:30 UTC, jonathanmcdaniel approved these changes
Nice work 💯

2021-02-07 15:30 UTC, gateship1 approved these changes

2021-02-09 23:21 UTC, coxwm11 approved these changes

2021-02-09 23:24 UTC, merged