updated frontend to use event instead of class
2020SE691T2/RecessApplication pull request #159
Opened 2021-03-05 00:46 UTC by gateship1

associated with backend pull request #88

2021-03-05 00:49 UTC, msknobloch2 requested changes

2021-03-05 00:49 UTC, msknobloch2 commented on src/Components/ViewEvent.jsx
> +    this.changeeventId = this.changeeventId.bind(this);
capitalize Event

2021-03-05 00:49 UTC, msknobloch2 commented on src/Components/ViewEvent.jsx
> +  changeeventId(event) {
capitalize Event

2021-03-05 00:49 UTC, msknobloch2 commented on src/Components/ViewEvent.jsx
> +                  <Form.Control type="text" name="eventIdInput" disabled={this.state.disabled} value={this.state.eventId} onChange={this.changeeventId} />
capitalize Event

2021-03-05 00:59 UTC, gateship1 commented on src/Components/ViewEvent.jsx
> +                  <Form.Control type="text" name="eventIdInput" disabled={this.state.disabled} value={this.state.eventId} onChange={this.changeeventId} />
accepted

2021-03-05 01:00 UTC, gateship1 commented on src/Components/ViewEvent.jsx
> +  changeeventId(event) {
accepted

2021-03-05 01:00 UTC, gateship1 commented on src/Components/ViewEvent.jsx
> +    this.changeeventId = this.changeeventId.bind(this);
accepted

2021-03-05 01:02 UTC, msknobloch2 requested changes
i think you made it worse

2021-03-05 01:58 UTC, msknobloch2 approved these changes

2021-03-05 18:17 UTC, coxwm11 approved these changes

2021-03-05 23:49 UTC, jonathanmcdaniel approved these changes

2021-03-06 01:51 UTC, jdurelli approved these changes

2021-03-07 20:53 UTC, merged